language: python
python:
  - "2.7"
services:
  - sqlite3
install:
  - pip install -r requirements.txt
before_script:
  - echo -e "\nclass DisableMigrations(object):\n    def __contains__(self, item):\n        return True\n    def __getitem__(self, item):\n        return 'notmigrations'\nMIGRATION_MODULES = DisableMigrations()" >> ./ecs/local_settings.py
script: "./manage.py test"

