# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_candidates_and_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='soc_id',
            field=models.IntegerField(null=True),
        ),
    ]
