# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_candidate_soc_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preference',
            options={'ordering': ['preference']},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecs.Point'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecs.Point'),
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
